[build]
# if commit is not tagged don't build
# ignore = "git describe --exact-match --tags HEAD && exit 1 || exit 0"
# publish = "site"
# command = "pip install -r requirements.txt && mkdocs build --clean"

[build.environment]


# The magic for deploying previews of branches
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"
command = "pip install -r requirements.txt && mkdocs build --clean"
