[default]
host = "server.com from TOML"
port = 5000.0
username = "admin"
PASSWORD = "Secret"
levels = [
  "debug",
  "info",
  "warning"
]
money = 500.5
age = 42.0
enabled = true
works = "toml_example"
custom = 'this is custom from [default]'
prefix_custom = "this is custom when we set a prefix"

  [default.test_loaders]
  dev = "test_dev"
  prod = "test_prod"

[development]
custom = "this is custom from [development]"
host = "dev_server.com from toml"
works = 'toml_example in dev env'

[production]
custom = "this is custom from [production]"
host = "prod_server.com from toml"
works = 'toml_example in prod env'
